### ISSUE TITLE
ServerSide event

### ISSUE THREAD

**Issue by amereii** [adtrace/adtrace_sdk_web#3]
@arefhosseini سلام
من میخوام سمت سروری یک سری ایونت مالی بفرستم که درآمد از ریسورس های مختلف مشخص بشه

دلیل اینکه کلاینتی نمیفرستم اینه که اپلیکیشن ما پیچیدگی های خاصی داره و خیلی حالت ها رو کلاینت نمیتونه هندل کنه

سوالم اینه که 
اولا چطوری میشه سروری ایونت فرستاد؟ سرور هم نود جی اس هست ، داکیومنتی دارید؟
دوما چطوری سرور ما میتونه از کلاینت یه سری متغیر دریافت کنه که بتونیم از سمت سرورمون به شما ارسال کنیم تا ریسورس های مختلف رو ترک کنیم؟

ببخشید که توی متن از لغات تخصصی انگلیسی استفاده نکردم و همه رو فارسی نوشتم چون گیت هاب همه چیز رو چپ به راست نشون میده خوندنش سخت میشه

**Comment by namini40** [comment]
سلام ممنون از توجه نظرتون. برای توضیحات کامل درباره این موضوع لطفا با پشتیبانی ما تماس بگیرید.
